name: Brandon Curtis
markdown: kramdown
encoding: utf-8
timezone: America/Los_Angeles
baseurl: "/wiki"

collections:
  wikipages:
    output: true
  wikihubs:
    output: true

gems:
  - jekyll-seo-tag
