name: Brandon Curtis
markdown: kramdown
encoding: utf-8
timezone: America/Los_Angeles
baseurl: "/wiki"
url: https://brandoncurtis.github.io/wiki
logo: /images/bc-suit.jpg
description: BC Wiki. tech, finance, and nonsense via GitHub Pages.

collections:
  wikipages:
    output: true
  wikihubs:
    output: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed

jekyll-mentions:
  base-url: https://github.com

feed:
  path: /feed.xml

