---
title: Wiki
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wikihubs:
    title: Wikihubs
    output: true
  wikipages:
    title: Wikipages
    output: true
name: Brandon Curtis
markdown: kramdown
encoding: utf-8
url: http://bcwiki.brandoncurtis.com
baseurl: http://bcwiki.brandoncurtis.com
logo: "/images/bc-suit.jpg"
description: BC Wiki. tech, finance, and nonsense via GitHub Pages.
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-mentions
- jekyll-feed
jekyll-mentions:
  base-url: https://github.com
feed:
  path: "/feed.xml"
